### ISSUE TITLE
Attribution report delay > 48hrs

### ISSUE THREAD

**Issue by cedelman** [privacycg/private-click-measurement#100]
It's expected attribution reports send after the 24-48 reporting delay window if Safari is closed. During testing it was discovered many reports were not delivered until roughly one month later. The graph below shows a trend of a trigger data value (gray line) over time after the value was removed from trigger logic on 1/25. It is a concern so many reports deliver after 48 hours. Has this behavior been noticed in any testing for other PCM API users?

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/101671509/159360587-2527bca7-fb8e-4f13-a0ee-9ea644225e9c.png">

1) Is there a test/debug solution that can be built into PCM to track at a finer grain level to help debug? Current debug solutions automatically send reports which isn't helpful to test reporting delay.
2) Event level reports that are received much later than 48 hours may not be useful for certain reporting use cases. Could reports older than a threshold outside the 48 hour window be dropped if desired, either by default or via a config set on the source event?

**Comment by johnwilander** [comment]
This looks like a Safari/WebKit-specific report. This GitHub repo is for the standards discussion, not specific engine implementations. Please file at https://bugs.webkit.org and cc me. Thanks!
