### ISSUE TITLE
In-App PCM Bug

### ISSUE THREAD

**Issue by FengAtPinterest** [privacycg/private-click-measurement#106]
Hi PCM team,
There might be a bug in the in-app PCM. [Here](https://github.com/FengAtPinterest/PCMoc) is my test demo project.
In the demo, the app-to-safari PCM works well, but the in-app PCM does not.

There are two same steps for the app-to-safari PCM and the in-app PCM. 
1. Create UIEventAttribution
2. Create UIEventAttributionView and cover it on the button

The bug must be in Step 3: Open SVC with UIEventAttribution in its configuration.

And I have added a breakpoint to `safariViewControllerDidFinish` and made sure the attribution data exists in `SFSafariViewController`

Since the `SFSafariViewController` does have the attribution data, it should store a PCM click, but it does NOT.

Can anyone help me with this? Is it my mistake, or is there a bug in `SFSafariViewController`?

**Comment by johnwilander** [comment]
This repo is for the web standards proposal. App-to-web is not part of that and bugs in individual implementations are not either. Please file with Apple. Thanks!
