### ISSUE TITLE
App <=> Web click attribution

### ISSUE THREAD

**Issue by benjaminsavage** [privacycg/private-click-measurement#19]
This proposal is primarily focused on ads shown on websites, leading to conversions that are generated on advertiser websites. Has the team considered the usecase of ads shown within native apps, leading to conversions that are generated on advertiser websites? This is a very common usecase.

In the case of a mobile phone, it seems that this usecase could be supported by up-leveling the storage of clicks requesting attribution from the browser to the operating system. For example on iOS, clicks on ads in native apps could also produce similar triples of information (campaignID, destination_website, click_source_app). If the browser could check a unified set of clicks requesting attribution, some generated in Safari, others generated in mobile apps, it would support this important usecase - while maintaining the same privacy guarantees.

I think building out first-class support for this usecase (native ads promoting advertiser websites) would be superior to developers attempting to build out various hacks to achieve this goal, both from a user experience as well as a "supporting legitimate business usecase" perspective.

**Comment by johnwilander** [comment]
Thank you, Ben! And sorry for my very late response. 🙄 What you bring up is interesting. However, we'd like to keep this as a web-only spec so I'll close this as being out of scope.
