### ISSUE TITLE
Consider reducing the ad attribution data budget to 3 bits

### ISSUE THREAD

**Issue by johnwilander** [privacycg/private-click-measurement#28]
(And bumping the campaign ID budget up accordingly.)

PCM proposes a 6-bit value encoding the conversion on the click destination side. The Click Through Conversion Measurement Event-Level API proposal has a corresponding 3-bit value called `conversion-metadata`. Ideally, we’d reconcile this into something simple for developers.

To discuss:

* Would 3 bits on click destination side work across the board? PCM would obviously be fine with it since it reduces entropy.
* PCM would probably consider a bump on the click source side to 8 bits if 3 bits were agreed upon on the click destination side. Would that we welcome?

**Comment by johnwilander** [comment]
Ping @michaelkleber @csharrison.

**Comment by benjaminsavage** [comment]
> PCM would probably consider a bump on the click source side to 8 bits if 3 bits were agreed upon on the click destination side. Would that we welcome?

The discussion on #11 indicated support for a 4+4+4 split (so potentially 8 and 4). I would welcome that. 

In practice, the 64 ad campaigns limit will be more problematic for us than the reduction in the fidelity of the conversion value.

**Comment by jinghao** [comment]
Agreed with @benjaminsavage. Larger domains will have a lot of campaigns, especially the marketplaces like Target or Shopify that have lots of uncoordinated advertisers running their own campaigns. My preference would be 9-3 over 6-6 because that would give us ~500 campaigns per domain and also align the conversion metadata spec with the Chrome proposal.

**Comment by jinghao** [comment]
@johnwilander Hi! For planning purposes, it would be helpful to understand where we ended up here. Thanks!

**Comment by minghaocwang** [comment]
hi, @johnwilander and @hober, given this issue is opened for quite a long time, any updates? Are we decided to pursue 8 bits (campaign id budget) and 3 bits (attribution data budget) ? Or should we still stay with 6 bits + 6 bits? Thanks.

**Comment by johnwilander** [comment]
I landed 8+4 bits for PCM in WebKit today: https://trac.webkit.org/changeset/270456

That is, 8 bits for the source ID (previously campaign ID) and 4 bits for the trigger data (previously conversion value).

**Comment by johnwilander** [comment]
This has now been updated in the spec too: https://github.com/privacycg/private-click-measurement/commit/f7e51bebbedc90419d6e39ea7cebb1d8ab687cc3
