### ISSUE TITLE
Move to the Privacy CG?

### ISSUE THREAD

**Issue by hober** [privacycg/private-click-measurement#32]
In privacycg/proposals#1, I've proposed moving this spec from @WICG to the @privacycg. What do current contributors think? How about you, @johnwilander?

**Comment by johnwilander** [comment]
I’m all for it. Jason no longer works on the draft and should be removed as editor.

**Comment by hober** [comment]
> Jason no longer works on the draft and should be removed as editor.

I'll submit a PR to reflect this.

**Comment by hober** [comment]
Done. I went ahead and merged it too; hope that's okay.

**Comment by hober** [comment]
In privacycg/proposals#1 the Privacy CG has decided to adopt PCM as a work item of the group. I'll take care of the migration soon.

**Comment by hober** [comment]
The spec's been transferred. Closing.
