### ISSUE TITLE
Browser closed after the conversion ?

### ISSUE THREAD

**Issue by HeyMultiverse** [privacycg/private-click-measurement#34]
Hello WICG Team, 

I am working on debugging Webkit's Privacy Preserving ad click attribution and trying to reproduce a scenario of closed browser after conversion happened. 

What is the expected behavior when the browser is closed after conversion and reopened after >48 hours ? I'm assuming it should essentially send the conversion attribution POST method (step 3) as soon as the browser is reopened. 

I tried to repro the scenario - after conversion in step 2, I closed the browser for more than 48 hours, and reopened it => I didn't receive step 3 HTTP Post request. This is non-debug mode where the timer is not set to 60 Seconds.

**Comment by johnwilander** [comment]
Hi!

I assume you've turned on the experimental feature and are testing it. Pending ad clicks and scheduled reports are only kept in-memory in the current implementation. Once we have reached consensus, we'll add a persistence layer along with the other changes.

**Comment by othermaciej** [comment]
Also, if this is about the implementation rather than the spec, it should probably be filed on bugs.webkit.org, not here.

**Comment by HeyMultiverse** [comment]
@johnwilander, Thanks for the clarification John. Are you folks, at some point, planning to open up the pending ad-clicks and scheduled-reports to be queried in debug mode(in browser console or syslog) ? Would be super helpful as we are developing features with ad-click attribution. (P.S: I work for Facebook and we are developing features for ad-click attribution.) 

@othermaciej, I was not sure if this was a bug or something that was not called out in the proposal. So posted here. Will make a note to file a bug.

**Comment by hober** [comment]
Duping to #21.
