### ISSUE TITLE
Ad-click Attribution when the href link opens in a new window ?

### ISSUE THREAD

**Issue by HeyMultiverse** [privacycg/private-click-measurement#50]
Hello Team, 

I'm testing [Private click measurement](https://webkit.org/blog/8943/privacy-preserving-ad-click-attribution-for-the-web/) feature. I have enabled experiment features for `adclick attribution` &  `adclick attribution debug mode` in Latest Safari Tech Preview Browser version: `Release 109 (Safari 14.0, WebKit 15610.1.17.2)`. 

When trying to repro(in localhost) the ad click attribution behavior per the proposal (with redirect and waiting on step 3) -- I load the href link in the same window, I get everything as expected -- Storing ad click, redirect and attribution call after 60 seconds. [console logs](https://user-images.githubusercontent.com/2718218/87091235-2f68dc80-c1ee-11ea-8750-ae9abe997353.png) 

when I load the ad click on a new window(`target="_blank"`) as the typical behavior in from publisher page, I don't see the repro for Step 1( and subsequently for step 2 and 3). 

Do I have to set something to get ad-click attribution across windows or Is this in still in development to support other windows ?

**Comment by johnwilander** [comment]
Hi! Thanks for experimenting. This sounds like a bug to me. Please file at https://bugs.webkit.org. You can cc me directly on the bug. Closing this issue since I don't think it has any impact on the proposed spec.
