### ISSUE TITLE
click-bots run rampant?

### ISSUE THREAD

**Issue by AubreyJaffer** [privacycg/private-click-measurement#55]
I think that moving attribution into the browser and limiting information to 6 bits per attribution 
is an unworkable combination because click-bots posing as browsers could send unlimited numbers of attributions to their targets.  Advertisers need to know, not only that they received attributions, but that the attributions they received are genuine.

**Comment by johnwilander** [comment]
Hi! Thanks for filing. Please see https://github.com/privacycg/private-click-measurement/issues/27.
