### ISSUE TITLE
Link attributes naming

### ISSUE THREAD

**Issue by johnwilander** [privacycg/private-click-measurement#56]
In https://github.com/privacycg/private-click-measurement/issues/30 we're getting close to final naming for the fields in the JSON attribution report. We should align the link attribution names with that. However, we may need some name spacing or context there. In the case of the JSON report, context is provided but the .well-known URL path but link attributes are stand-alone.

adCampaignID –> attributionContentID?
adDestination –> attributionDestination?

What do you think, @csharrison?

**Comment by csharrison** [comment]
cc @johnivdel @maudnals

Namespacing to "attribution" sounds good to me to make it clear this is the API about attribution. We were thinking of renaming our proposal to "Attribution Reporting API" which makes "attribution" a good sign-posting prefix.

One nit: Attribute names should not be camel-case. They should be lower-case concatenated. See [naming principles from TAG](https://w3ctag.github.io/design-principles/#casing-rules).

**Comment by johnivdel** [comment]
In #30 the proposed field for the site attribution triggers on is "attributed-on-site", which is the same value as attributionDestination. It would be nice to coalesce these.

In [this issue](https://github.com/WICG/conversion-measurement-api/issues/57#issuecomment-700912187) we proposed  "attributeon" for the link attribute which would match the JSON field.

For "attributionContentID", the field is "source-id", so maybe "attributionsourceid"? (or "attributesourcedata" % the discussion in #30).

**Comment by johnwilander** [comment]
> cc @johnivdel @maudnals
> 
> Namespacing to "attribution" sounds good to me to make it clear this is the API about attribution. We were thinking of renaming our proposal to "Attribution Reporting API" which makes "attribution" a good sign-posting prefix.

👍🏼

> One nit: Attribute names should not be camel-case. They should be lower-case concatenated. See [naming principles from TAG](https://w3ctag.github.io/design-principles/#casing-rules).

Yeah, there was some back and forth early on but I do know my IDL additions are all lower case.

> In #30 the proposed field for the site attribution triggers on is "attributed-on-site", which is the same value as attributionDestination. It would be nice to coalesce these.
> 
> In [this issue](https://github.com/WICG/conversion-measurement-api/issues/57#issuecomment-700912187) we proposed "attributeon" for the link attribute which would match the JSON field.

Just to make sure, this is "attribute on" concatenated because it's not been attribute**d** yet? If so, sounds good.

> For "attributionContentID", the field is "source-id", so maybe "attributionsourceid"? (or "attributesourcedata" % the discussion in #30).

🤦🏻‍♂️ I went too quickly here. My earlier JSON proposal was for content ID but you're right. attributionsourceid it is.

**Comment by johnivdel** [comment]
> Just to make sure, this is "attribute on" concatenated because it's not been attributed yet? If so, sounds good.

Yes, that was our thinking as well.

**Comment by johnwilander** [comment]
This has now been updated in the spec: https://github.com/privacycg/private-click-measurement/commit/f7e51bebbedc90419d6e39ea7cebb1d8ab687cc3
