### ISSUE TITLE
Legacy Triggering to third parties

### ISSUE THREAD

**Issue by dialtone** [privacycg/private-click-measurement#68]
Reading the spec I'm a bit confused by the role of triggering the conversion and the ad source url. Technically speaking the majority of publishers are never really involved in any decision about which ad to show, they have just installed the JS snippet from the ad network and generate clicks via this method.

Somehow the reading of the specification seems to indicate that the publisher in question would be responsible for setting up this `.well-known` URL and/or redirect to the right destination based on the exact ad that was displayed on their page at that time, on which they won't have any information about because this data is inside the SSP that put the ad there.

Ultimately this seems to really only work if you are a big enough publisher and own an exchange, which is basically Facebook and Google and perhaps a few of the other big publishers like NYT/WaPo, but in all cases in which the ad was put there by the DSP/SSP whose domain doesn't match `social.example` or `search.example`  you end up being unable to trigger such an event in a legacy scenario.

I understand there's a modern way to do this but the legacy seems to be purely thought for big networks or publishers.

**Comment by johnwilander** [comment]
A lot of this will be resolved by sending attribution reports to the advertiser: https://github.com/privacycg/private-click-measurement/issues/53. That would mean that websites running ads wouldn't need to care about reporting at all for the purposes of the advertiser knowing where click-through ads leading to conversions are placed.

**Comment by johnwilander** [comment]
The work needed to address this is tracked in other issues. Closing.
