### ISSUE TITLE
Future of Granular conversion level measurement from Advertiser's website.

### ISSUE THREAD

**Issue by Vishnu-r-prasad** [privacycg/private-click-measurement#74]
Hi John/All,

As an established measurement company, we currently capture details of online conversions on a real-time basis from the brand's conversion page using a conversion pixel.

These conversion pixels share passback information which may include order id, revenue & Advertiser first party ids (at a user level granularity) on a real time basis. After reviewing the PCM(private click measurement) documentation, we don’t have clarity on whether this will be allowed in Safari in the post-cookie world.

From the PCM proposal, we understand that there is a provision to send an attribution report to a well-known location. However we understand that this will be delivered only with delay and in an aggregated manner. So information at an individual conversion level will not be available.  I also see that a java script API has been introduced to capture conversion data with a limited entropy of data. 

Naturally the question arises if Safari/webkit would bring in some restrictions in firing a tracking pixel or conversion pixel itself from the page. The pixel call is essentially a third party http request to the measurement vendor’s domain. Blocking these would be a much bigger change than just blocking of third party cookies. Hence we wanted to reach out for clarity on this topic.

Please review and let me know of any perspective that you may have on this topic. In case we are bringing restrictions in firing tracking pixels and conversion pixels, it would be good to get a high level timeline if available. Please let me know if you need more information on any of these topics.

Thanks,
Vishnu

**Comment by johnwilander** [comment]
> Hi John/All,
> 
> As an established measurement company, we currently capture details of online conversions on a real-time basis from the brand's conversion page using a conversion pixel.
> 
> These conversion pixels share passback information which may include order id, revenue & Advertiser first party ids (at a user level granularity) on a real time basis. After reviewing the PCM(private click measurement) documentation, we don’t have clarity on whether this will be allowed in Safari in the post-cookie world.

This repository is for the proposed standard Private Click Measurement, or PCM. For browser (engine) specific issues, please use their respective issue tracker. For WebKit you can use https://bugs.webkit.org.

> From the PCM proposal, we understand that there is a provision to send an attribution report to a well-known location. However we understand that this will be delivered only with delay and in an aggregated manner. So information at an individual conversion level will not be available. I also see that a java script API has been introduced to capture conversion data with a limited entropy of data.

The JavaScript API has not yet been specified or implemented.

> Naturally the question arises if Safari/webkit would bring in some restrictions in firing a tracking pixel or conversion pixel itself from the page. The pixel call is essentially a third party http request to the measurement vendor’s domain. Blocking these would be a much bigger change than just blocking of third party cookies. Hence we wanted to reach out for clarity on this topic.

Currently, PCM _relies_ on third-party HTTP GET requests as a mechanism to trigger attribution. We want to add a [JavaScript API](https://github.com/privacycg/private-click-measurement/issues/31) and a [same-site "pixel" conversion method](https://github.com/privacycg/private-click-measurement/issues/71) with which the advertiser can convert whatever it wants, including wild card '*', and there will be no more need for third-party tracking pixels.

As to whether a particular browser may block tracking pixels or not, you'd have to ask that browser.

> Please review and let me know of any perspective that you may have on this topic. In case we are bringing restrictions in firing tracking pixels and conversion pixels, it would be good to get a high level timeline if available. Please let me know if you need more information on any of these topics.
