### ISSUE TITLE
how conversion reporting happens when the browser is not running

### ISSUE THREAD

**Issue by leviduan** [privacycg/private-click-measurement#77]
Hi everyone,

Once a triggering event matches a stored click, a single attribution report is scheduled by the browser to be sent out randomly between 24 and 48 hours later, or the earliest time thereafter when the browser is running. As long as an attribution report has not yet been sent, it can be rescheduled based on a triggering event with higher priority.

What happens if a conversion event is scheduled but the safari of iPhone is not opened at this time? if iPhone users never use safari, the attribution report never been sent?

**Comment by leviduan** [comment]
safari on the iPhone always running in the background? or not? if the user closes safari on the iPhone, a single attribution report how the browser to be sent out randomly between 24 and 48 hours later if the user never open safari.

**Comment by johnwilander** [comment]
Hi! This group is the Privacy CG. WICG is something else.

If you have specific questions on WebKit’s implementation of PCM, please file at https://bugs.webkit.org.

In terms of the PCM spec, I think it’s clear. If the browser is not running, it is free to not send attribution reports. It is also free to schedule reports in some fashion that allows them to be sent even when the browser is not running.

**Comment by leviduan** [comment]
> Hi! This group is the Privacy CG. WICG is something else.
> 
> If you have specific questions on WebKit’s implementation of PCM, please file at https://bugs.webkit.org.
> 
> In terms of the PCM spec, I think it’s clear. If the browser is not running, it is free to not send attribution reports. It is also free to schedule reports in some fashion that allows them to be sent even when the browser is not running.

It is also free to schedule reports in some fashion that allows them to be sent even when the browser is not running. How to do it? PCM reply on Safari, if I would close Safari on iPhone, how to send attribution reports?

**Comment by johnwilander** [comment]
Computers can run background processes for such purposes.

**Comment by leviduan** [comment]
> Computers can run background processes for such purposes.

iPhone can？I don't know if Safari always runs in background processes.

**Comment by johnwilander** [comment]
I’m not talking about specific hardware or devices. PCM is a web platform spec meant to be implementable in any browser. If the platform supports background processing and the browser vendor wants, attribution reports can be sent without the browser being in use. The spec doesn’t mandate such functionality but also doesn’t advise against it.
