### ISSUE TITLE
Relation of attributiondestination to href

### ISSUE THREAD

**Issue by ekr** [privacycg/private-click-measurement#85]
Suppose we have an <a> tag with both ```attributiondestination``` destination and ```href``` what is the behavior of the click? Is ```href``` ignored by supporting browsers?

**Comment by johnwilander** [comment]
`attributiondestination` is for the destination landing site whereas `href` can take the user to an interstitial. PCM will only accept click measurement data if the user indeed did land on `attributiondestination`.

**Comment by ekr** [comment]
Are there any restrictions on ```href```  at all? Suppose the I have 

```<a href="example.com/go-to-example.org" attributiondestination="example.org">```

Is that valid as long as ```example.com``` redirects?

**Comment by johnwilander** [comment]
> Are there any restrictions on `href` at all? Suppose the I have
> 
> `<a href="example.com/go-to-example.org" attributiondestination="example.org">`
> 
> Is that valid as long as `example.com` redirects?

By spec, yes.

**Comment by ekr** [comment]
Thank you.
