### ISSUE TITLE
Lowercase or camelcase anchor attributes?

### ISSUE THREAD

**Issue by johnwilander** [privacycg/private-click-measurement#90]
We should align on casing for our HTML anchor attributes. Such as:
- `attributionsourceid`  or `attributionSourceId`
- `attributiondestination` or `attributionDestination`
- `attributionsourcenonce` or `attributionSourceNonce`

Here's where we are today:
- [PCM spec](https://privacycg.github.io/private-click-measurement/#linkformat) both lowercased and camelcased
- [WebKit's blog post](https://webkit.org/blog/11529/introducing-private-click-measurement-pcm/) lowercased
- [ARA spec](https://wicg.github.io/conversion-measurement-api/#monkeypatch-anchor) both lowercased and camelcased
- [ARA explainer](https://github.com/WICG/conversion-measurement-api/blob/main/event_attribution_reporting_clicks.md#attribution-source-declaration) lowercased

The HTML spec is not super clear but looks to lean toward lowercase:
- https://html.spec.whatwg.org/multipage/dom.html#attributes
- https://html.spec.whatwg.org/multipage/syntax.html#attributes-2
- https://html.spec.whatwg.org/multipage/indices.html#attributes-3

Maybe there is a clear directive that I have missed?

(This issue mirrors the one I [filed on ARA](https://github.com/WICG/conversion-measurement-api/issues/238).)

**Comment by johnwilander** [comment]
Ping @annevk and @hober who've provided valuable input on this previously.

**Comment by gsnedders** [comment]
Are we talking about the HTML attributes or the WebIDL attributes here?

HTML attributes are converted by the parser to lowercase, so I'd expect us to use lowercase there (as otherwise you could only set the attributes through the DOM).

For WebIDL there's no case-conversion done, so that's where the question is, right?

**Comment by johnwilander** [comment]
TAG prefers lowercase: https://w3ctag.github.io/design-principles/#casing-rules

As pointed out by Charlie in https://github.com/WICG/conversion-measurement-api/issues/238#issuecomment-929651243.

**Comment by johnwilander** [comment]
Lowercase means I should fix the spec.

**Comment by gsnedders** [comment]
The status quo seems to be:

 * PCM spec: HTML attribute lowercased, WebIDL attribute camel-cased
 * WebKit's blog post: HTML attribute lowercased, no WebIDL interface mentioned
 * ARA spec: HTML attribute lowercased, WebIDL attribute camel-cased
 * ARA explainer: HTML attribute lowercased, no WebIDL interface mentioned

> TAG prefers lowercase: https://w3ctag.github.io/design-principles/#casing-rules

For the HTML attribute yes, and prefers camel-case for WebIDL attributes. Which implies the spec is right.

**Comment by johnwilander** [comment]
> For the HTML attribute yes, and prefers camel-case for WebIDL attributes. Which implies the spec is right.

Oh, you're referring to programmatic accessors such as `element.attributionSourceId`?

**Comment by annevk** [comment]
Yeah, those are called IDL attributes in the HTML Standard. (The others are content attributes.)

**Comment by johnwilander** [comment]
Change landed in WebKit: https://trac.webkit.org/changeset/283342/webkit
Resolving.
